import os
from os import getenv
from dotenv import load_dotenv

load_dotenv()
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "AgBqjVRV3pdP-Vg7esUHcJl9mxDc-jQoGxRr3TBOO9ewSpuzmo8p5EuElw4hhap9rhQuFV78BDAEsUjoXWL-YzW1lfo0el1kWOgtXQnnlXS32Gt-3jvBOselQHT9MWRPFm9eCXWRnf099YaN16leQIhJyLJStgWv05JKZ0kwd4M5WCAFmcFis4DPnYj3IkzrTyw8lUGmdGvAYauLsMNXLkD6S46krgvdQwo98_iA-xryow3PHTZZjTZP8nRLtuquYrzL8kXr2CVlr43xl5mVCwPwqC_UIlG0X_mqvVVgE8UoCYVpr_oO_TKYP2sTbyopZRi3Mz9gO2ZWDZMhccwFgRbSAAAAAVm0DL4A")
BOT_TOKEN = getenv("BOT_TOKEN","5649188759:AAFCVbZmDJ7aOqaQzAWTgh3fL8bBYDwnqHc")
BOT_NAME = getenv("BOT_NAME", "Dozaxkurdi")
API_ID = int(getenv("API_ID", "13980703"))
API_HASH = getenv("API_HASH","8739dceb2d5ee894b67b106efc50d52c")
MONGODB_URL = getenv("MONGODB_URL", "Dozax")
OWNER_NAME = getenv("OWNER_NAME", "Dozax1")
ALIVE_NAME = getenv("ALIVE_NAME", "Dozaxkurdi")
BOT_PHOTO = getenv("BOT_PHOTO", "Dozaxkurdi")
DEV_PHOTO = getenv("DEV_PHOTO", "Dozaxkurdi")
DEV_NAME = getenv("DEV_NAME", "Dozaxkurdi")
BOT_USERNAME = getenv("BOT_USERNAME", "Dozaxkurdi")
UPSTREAM_REPO = getenv("UPSTREAM_REPO", "")
UPSTREAM_BRANCH = getenv("UPSTREM_BRANCH", "main")
ASSISTANT_NAME = getenv("ASSISTANT_NAME", "kurdi_sport")
GROUP_SUPPORT = getenv("GROUP_SUPPORT", "Dozax77")
UPDATES_CHANNEL = getenv("UPDATES_CHANNEL", "Dozax77")
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "5703797578").split()))
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "/ ! .").split())
ALIVE_IMG = getenv("ALIVE_IMG", "https://telegra.ph/file/c118c574c4fadfd656a74.jpg")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "900"))
UPSTREAM_REPO = getenv("https://github.com/pqnzbmmwQ92/ll")
IMG_1 = getenv("IMG_1", "https://telegra.ph/file/8efbe93b81985bb648d95.jpg")
IMG_2 = getenv("IMG_2", "https://telegra.ph/file/8efbe93b81985bb648d95.jpg")
IMG_3 = getenv("IMG_3", "https://telegra.ph/file/8efbe93b81985bb648d95.jpg")
IMG_4 = getenv("IMG_4", "https://telegra.ph/file/8efbe93b81985bb648d95.jpg")
IMG_5 = getenv("IMG_5", "https://telegra.ph/file/8efbe93b81985bb648d95.jpg")
